### ISSUE TITLE
yq "latest" fails when the tag is created but the release isn't showing up

### ISSUE THREAD

**Issue by MikeJansenNextira** [eitsupi/devcontainer-features#103]
Today when rebuilding my devcontainer with this feature and `YQ_VERSION` = `latest`, I had an error with tar ending unexpectedly.  

The `YQ_VERSION` showing in the log was `4.40.6`.  Looking at the yq repo, [4.40.5](https://github.com/mikefarah/yq/releases/tag/v4.40.5) was showing up as latest.  4.40.6 was not under "Releases" but was under ["Tags"](https://github.com/mikefarah/yq/releases/tag/v4.40.6).

Also, the "Tagged" release for 4.40.6 only had source archives and no binary archives.

I worked around by changing `YQ_VERSION` to `4.40.5` in my `devcontainer.json`.

**Comment by eitsupi** [comment]
Thanks for reporting this, could you please ask yq's repo to remove the tag or create a release?
I don't think there is anything we can do here.

**Comment by eitsupi** [comment]
I think the latest yq relase solved this issue.

**Comment by MikeJansenNextira** [comment]
Looking into it, the problem is if any repo creates a tag that matches `v*` but doesn't create a release, the error will occur.  From your side, the only way to resolve that for `latest` would be going by GitHub releases instead of tags.

Since it's not a contract (that I'm aware of) that if a repo is tagged it must have a corresponding release, it's not a bug in the target repo (`yq` in this case).  

I'll still raise an issue as a question on `yq` repo to ask if that's an expected flow.  I haven't delved into other dev container extensions that support a "latest" to see how they handle GitHub tags/releases.

**Comment by eitsupi** [comment]
The GitHub API must be used to check for GitHub releases, but we prefer not to use it as much as possible because of the limited number of accesses. This is why we use tags instead of releases. (c.f. devcontainers/features#458)

So the only possible option is to fall back to querying the GitHub API if a tag exists but cannot be downloaded.
If anyone wants to implement that, PR is welcome!
